language: python
install:
 - pip install --upgrade pip
 - pip --version
 - pip install tensorflow
 - pip install -r python/script/requirements.txt
script:
- cd python
- python train_text_classification.py --num_epochs 1
- python train_sequence_tagging.py --num_epochs 1
 
